### ISSUE TITLE
Added one issue,60% done - project progress bar still shows 0%

### ISSUE THREAD

**Issue by tomyfranncy** [stgeneral/redmine-progressive-projects-list#10]
Added one issue,60% done - project progress bar still shows 0%

version 0.10

**Comment by Saylrman64** [comment]
Hello again,

What I was looking for (and maybe others are too) is specifically how the progress % is determined.
Please correct me if I am wrong but in addition to the explination above I offer this:
It looks like the Progress Bar (lighter color) is estimated by adding the % done for each issue and dividing by the number of issues. Issues that are in Closed status = 100% no matter what the % Done slider inside the Issue shows. This progress bar does not care about estimated time.
The % field is estimated hours total divided by number of open tickets.
See code snippet below for he % complete math.

It would seem the % complete should take into account the Estimated and Spent Hours.
Is that also inherited from Redmine or is it only calculated in your project_decorator.rb?

Thanks again.

Code snippet from  redmine-progressive-projects-list/lib/progressive/project_decorator.rb
# Cloned from Version#issues_progress(open)
def issues_progress(open)
@issues_progress ||= {}
@issues_progress[open] ||= begin
progress = 0
if issues.count > 0
ratio = open ? 'done_ratio' : 100
done = issues.sum("COALESCE(CASE WHEN estimated_hours > 0 THEN estimated_hours ELSE NULL END, #{estimated_average}) * #{ratio}",
:joins => :status,
:conditions => ["#{IssueStatus.table_name}.is_closed = ?", !open]).to_f
progress = done / (estimated_average * issues.count)
end
progress
end
end

**Comment by stgeneral** [comment]
@Saylrman64 as you can see the code for this calculations was cloned from the Redmine core. I believe that code and plugin should share the same behavior. So, if any change to this logic needs any update this update should be added to the Redmine core first.

**Comment by Saylrman64** [comment]
Thank you @stgeneral 
If I wever get time or energy to make the estimation better, I will start with Redmine core.

Thanks again.

**Comment by ahsankhan201** [comment]
@stgeneral can we also show the number of inprogress issues, and resolved issues?

**Comment by stgeneral** [comment]
@ahsankhan201 Redmine has two high level statuses: 'open' and 'closed'. Other statuses ('In progress', 'Resolved', etc) are custom and should not be tracked by generic plugin.

**Comment by ahsankhan201** [comment]
@stgeneral  Thanks for your reply. but tell me how can i achive it by customise your plugin.
because i am a layman in redmine development.

**Comment by stgeneral** [comment]
@ahsankhan201 you may take a look and customize this lines:
- https://github.com/stgeneral/redmine-progressive-projects-list/blob/master/lib/progressive/projects_helper_patch.rb#L29
- https://github.com/stgeneral/redmine-progressive-projects-list/blob/master/lib/progressive/projects_helper_patch.rb#L41

**Comment by ahsankhan201** [comment]
@stgeneral Many Many Thanks for your quick response.
I change this line by your given line but it shows this error in logs.
ActionView::Template::Error (undefined local variable or method `version' for #<#<Class:0xc1de4ec>:0xc1e4928>):
    9: <h2><%= l(:label_project_plural) %></h2>
    10:
    11: <div id="projects-index">
    12: <%= render_project_hierarchy(@projects) %>
    13: </div>
    14:
    15: <% if User.current.logged? %>
  app/helpers/application_helper.rb:286:in `block in render_project_nested_lists'

**Comment by ahsankhan201** [comment]
@stgeneral can you help me out to customise these lines. which argument i can add for getting in progress issues.?

**Comment by stgeneral** [comment]
@ahsankhan201 I have no plan to add this feature to the plugin. So, you may feel free to update plugin as you like.
