### ISSUE TITLE
Progress bar and progress % do not match - how is the math done?

### ISSUE THREAD

**Issue by Saylrman64** [stgeneral/redmine-progressive-projects-list#41]
Hello,
I love this plugin but I need to be able to show my clients that it makes sense.
I often see project that show the bar 1/2 way across but the percent complete says 0%.
I've tried to fnd the documentation that explains how you calculate the % complete but I can not find anything.
I would gladly help update the documentation to explain the process or show how the % complete is calculated if you can tell me.

Thanks

**Comment by stgeneral** [comment]
@Saylrman64 please read comments for #10. Seems it should explain you how these progress bars work. Let me know if you still have any questions.

Thanks for loving my plugin :)

**Comment by Saylrman64** [comment]
I did and it helps.
Still some strange math.

Thank you!
