### ISSUE TITLE
Version progress bar not displayed for shared versions

### ISSUE THREAD

**Issue by romovs** [stgeneral/redmine-progressive-projects-list#42]
If you create a new version in project A with sharing set to "With all project" and assign this version to an issue in another project B, the version progress bar is not rendered for project B.

**Comment by stgeneral** [comment]
Yes, indeed. Plugin renders not only versions that belong to the project. Redmine does not provide any good method to calculate issues of shared version for current project. Adding version rendering and extra logic may cause slowing down rendering while it is not perfect (#33). So, I'm leaving it as is for now.
