### ISSUE TITLE
Progress bar exceeding container's width

### ISSUE THREAD

**Issue by jmfarina** [stgeneral/redmine-progressive-projects-list#43]
At least in conjunction with the Fedmine plugin (https://github.com/Froiden/fedmine), in the projects list view, the progress bar displayed was exceeding the width of each project's box, hence overlapping between projects.
To fix it, I tried editing lib/progressive/projects_helper_patch.rb and replacing the width, which was being set in two different places, from 30em to 100%. That seems to have fixed it, though I haven't tested it too much.

BTW, nice plugin, thank you!

**Comment by stgeneral** [comment]
@jmfarina thanks for interest to the plugin. 

This plugin works utilizes pieces of the original Redmine code to render progressbard. It works well with build in themes and several custom themes. So, probably it would be better if you cross-post this issue to https://github.com/Froiden/fedmine repository.
