### ISSUE TITLE
page can not be displayed after installation on projects link

### ISSUE THREAD

**Issue by frequency1** [stgeneral/redmine-progressive-projects-list#44]
ActionView::Template::Error (undefined method `closed_pourcent' for #<Version:0x007f1f981bb340>):
     9: <h2><%= l(:label_project_plural) %></h2>
    10:
    11: <div id="projects-index">
    12: <%= render_project_hierarchy(@projects) %>
    13: </div>
    14:
    15: <% if User.current.logged? %>
  app/helpers/application_helper.rb:279:in `block in render_project_nested_lists'
  app/helpers/application_helper.rb:264:in `each'
  app/helpers/application_helper.rb:264:in `render_project_nested_lists'
  app/views/projects/index.html.erb:12:in `_app_views_projects_index_html_erb___4548725850579294750_56385240'

**Comment by stgeneral** [comment]
@frequency1 what version of Redmine do you use?

**Comment by frequency1** [comment]
Redmine 3.0

**Comment by stgeneral** [comment]
Plugin was never tested against Remine 3.0. So, seems it is not compatible with it. I've created an issue #45 and will add Redmine 3.0 compatibility when have some time.

**Comment by stgeneral** [comment]
Issue was caused by closure of http://www.redmine.org/issues/12724.
