### ISSUE TITLE
redmine 3.0 配置2.0.1 版本插件后 项目进度条显示百分比错误，见插图！

### ISSUE THREAD

**Issue by xian-crazy** [stgeneral/redmine-progressive-projects-list#46]
![qq 20150518105736](https://cloud.githubusercontent.com/assets/6520452/7673810/ff271a16-fd4c-11e4-8a22-9dfb3b2c90be.png)

为什么显示的是100%呢

**Comment by stgeneral** [comment]
Looks like duplicate for #58, #49.

**Comment by stgeneral** [comment]
Fixed by #55.
