### ISSUE TITLE
v2.0.1 does not work with Redmine 3.0.3

### ISSUE THREAD

**Issue by Marqin** [stgeneral/redmine-progressive-projects-list#49]
I've updated Redmine to 3.0.3, and Your plugin to 2.0.1, and it shows "100%" for every project, even if it's not 100%:
![zrzut ekranu 2015-06-22 o 19 01 20](https://cloud.githubusercontent.com/assets/959429/8287681/8b8457be-1911-11e5-857b-4a79496f17fe.png)

**Comment by Marqin** [comment]
It looks like definitions of issues_completed_percent and issues_closed_percent are missing.

**Comment by Marqin** [comment]
It seem that some files are missing in v2.0.1 archive. Still, after installing from git HEAD it's showing 100% on all projects :disappointed:

**Comment by Marqin** [comment]
@stgeneral if this can be any help, I found project without closed issues:
![zrzut ekranu 2015-06-22 o 20 05 10](https://cloud.githubusercontent.com/assets/959429/8289029/1d28cf8a-191a-11e5-8224-23b75ac386bf.png)

**Comment by stgeneral** [comment]
Plugin was tested on Redmine 3.0.1. Did plugin work for you on 3.0.1 or 3.0.2?

**Comment by Marqin** [comment]
I've updated from 2.6.5, so I don't know.

**Comment by stgeneral** [comment]
It would be great if you could try it on the 3.0.1 and/or 3.0.2 in order we can localize the problem.

Also, can anybody else confirm any problems with 3.0.2 or 3.0.3?

**Comment by Marqin** [comment]
If this can help, this is HTML from that "Sender" project progress bar:
![zrzut ekranu 2015-06-23 o 12 07 28](https://cloud.githubusercontent.com/assets/959429/8303769/807c97d4-19a0-11e5-930d-f6b5108870aa.png)

**Comment by DavidLBCN** [comment]
I have the same problema. Status bar always shows 100%.
I use redmine versión 3.0.3

**Comment by of10** [comment]
Same problem for me. 

Using plugin version 2.0.1 and Redmine 3.0.3.

**Comment by sysgloo** [comment]
Same problem =(

Environment:
  Redmine version              3.0.3.stable.14416
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                    4.2.3
  Environment                    production
  Database adapter            Mysql2
SCM:
  Subversion                     1.8.8
  Git                                   1.9.1

**Comment by stgeneral** [comment]
Thanks everyone for the confirmation of the problem. Will take a look as soon as have some time.

**Comment by sysgloo** [comment]
Np! We will wait for the solution of the problem! Thx 4 all

**Comment by kakawait** [comment]
Same issue on 3.0.4 just FYI

**Comment by gatewaybeard** [comment]
![progress](https://cloud.githubusercontent.com/assets/13450674/8824244/f379c0d6-306b-11e5-9a0a-47e8950119ab.PNG)

I am experiencing the same issue.
No project has any closed issues
No project has any issues over 10%

Environment:
  Redmine version                3.0.4.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [i686-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Filesystem                     
Redmine plugins:
  progressive_projects_list      2.0.1
  redmine_agile                  1.3.9

**Comment by markus-fischbacher** [comment]
Same problem here.

Environment:
  Redmine version                3.1.0.stable.14506
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  progressive_projects_list      2.0.1

**Comment by jp-yendo** [comment]
It was confirmed operate in redmine3.1.0.
pull request one fix files.
Modified files to another has also been requested.

**Comment by Marqin** [comment]
@jp-yendo do not create pull request for every file. Pull request whole feature-branch - in Your case it would be 1 Pull Request for fixing that bug.

https://help.github.com/articles/using-pull-requests/

**Comment by jp-yendo** [comment]
sorry...
It does not make sense in the just started github.

**Comment by RayLLer** [comment]
Any advance on this issue

**Comment by stgeneral** [comment]
Fixed by #55. Thanks everybody for help and @jp-yendo for the fix.
