### ISSUE TITLE
404 - Version link produces error

### ISSUE THREAD

**Issue by pstamey** [stgeneral/redmine-progressive-projects-list#56]
If you click on version link you get a 404 with the following link https://xxx/versions/594

![image](https://cloud.githubusercontent.com/assets/1383244/10149935/91ead11e-65f1-11e5-9d12-9d195de5f116.png)

Page not found

The page you were trying to access doesn't exist or has been removed.

Back

Running Redmine 3.1.0

**Comment by stgeneral** [comment]
Link looks ok. Plugin does nothing with versions. Please try new version of the plugin (3.0.0) on the Redmine 3.2 and let me know if you still experience this issue.
