### ISSUE TITLE
All projects to 100%

### ISSUE THREAD

**Issue by shiningfm** [stgeneral/redmine-progressive-projects-list#58]
Hello
I use redmine 3.0.1 and this plugin version 2.0.1, and the progress bar is always at 100%, which is of course irrelevant in almost all cases.
The bar doesn't show when no issues are opened though, which I think is right.
Why does it happen? How can I repair?
Thanks

**Comment by stgeneral** [comment]
Seems that this problem was already reported #49. Also there is a pull request with a fix #55. You may try it but I haven't tested it.

Thank you.

**Comment by shiningfm** [comment]
Sorry I didn't notice the bug report! Thank you for still taking time to answer!
I tried the fix and it seems to be working for me (I haven't calculated but I now have values that seem correct).

Thanks again

**Comment by stgeneral** [comment]
Fixed by #55.
