### ISSUE TITLE
Redmine 3.1 Error

### ISSUE THREAD

**Issue by darioajr** [stgeneral/redmine-progressive-projects-list#59]
``````
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
``````

**Comment by stgeneral** [comment]
Any other details? Are you sure that the problem in the progressive-projects-list plugin?

**Comment by darioajr** [comment]
This erro occurred when I click on Top Menu (Projects) or Menu (Overview)

**Comment by stgeneral** [comment]
Unable to reproduce it on Redmine 3.2. Please provide details from the log file if you still experience this issue.
