### ISSUE TITLE
redmine 3.2 RoutingError

### ISSUE THREAD

**Issue by jeacott1** [stgeneral/redmine-progressive-projects-list#62]
catastrophic failure with latest version (release, and master) of this plugin installed with redmine 3.2.

ActionController::RoutingError (No route matches [POST] "/cgi-bin/php4"):
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by stgeneral** [comment]
`cgi-bin/php4` does not have any relation to this plugin.

**Comment by jeacott** [comment]
ok, so this plugin breaks something else. all works fine until this is installed. any thoughts?

**Comment by stgeneral** [comment]
@jeacott @jeacott1 this error can't be caused by the plugin itself. In the provided log there are no mentions of the plugin. Something in you system makes calls to `cgi-bin/php4`.

**Comment by jeacott** [comment]
ugh - just script kiddies bashing an open port. will find 'the relevant part' of the log and report back with something more sensible.

**Comment by jeacott** [comment]
ok, my bad. after finding the error in the nginx log.
  Message from application: Progressive Project List plugin directory should be 'progressive_projects_list' instead of 'redmine-progressive-projects-list-3.0.1' (RuntimeError)

'redmine-progressive-projects-list-3.0.1' is what the zip download from github unpacks to btw.
