### ISSUE TITLE
ActionView::Template::Error (undefined method `closed_pourcent'

### ISSUE THREAD

**Issue by daoth** [stgeneral/redmine-progressive-projects-list#63]
Started GET "/projects" for 113.185.6.37 at 2016-03-19 20:44:52 +0000
Processing by ProjectsController#index as HTML
  Current user: admin (id=1)
  Rendered projects/index.html.erb within layouts/base (211.9ms)
Completed 500 Internal Server Error in 243ms (ActiveRecord: 70.5ms)

ActionView::Template::Error (undefined method `closed_pourcent' for #<Version:0x007fdd6c77bf90>):
     9: <h2><%= l(:label_project_plural) %></h2>
    10:
    11: <div id="projects-index">
    12: <%= render_project_hierarchy(@projects) %>
    13: </div>
    14:
    15: <% if User.current.logged? %>
  plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:60:in `block in render_project_progress_bars'
  plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:53:in `render_project_progress_bars'
  plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:31:in `block in render_project_hierarchy_with_progress_bars'
  app/helpers/application_helper.rb:282:in `block in render_project_nested_lists'
  app/helpers/application_helper.rb:267:in `each'
  app/helpers/application_helper.rb:267:in `render_project_nested_lists'
  plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:21:in `render_project_hierarchy_with_progress_bars'
  app/views/projects/index.html.erb:12:in `_app_views_projects_index_html_erb__3813236679964995269_11550680'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I am using redmine 3.2.1
Could you help me to fix this issue.
Thank so much

**Comment by stgeneral** [comment]
I believe you are using the outdated version of the plugin. Please upgrade it to the latest version.

**Comment by benoitlm** [comment]
Hello,

I have install the last version on redmine 3.1.0 but the problem persist:

F, [2016-06-10T17:45:24.329137 #10055] FATAL -- :
ActionView::Template::Error (undefined method `closed_pourcent' for #<Version:0x000000074934d0>):
     9: <h2><%= l(:label_project_plural) %></h2>
    10:
    11: <div id="projects-index">
    12: <%= render_project_hierarchy(@projects) %>
    13: </div>
    14:
    15: <% if User.current.logged? %>
  app/helpers/application_helper.rb:280:in `block in render_project_nested_lists'
  app/helpers/application_helper.rb:265:in `each'
  app/helpers/application_helper.rb:265:in `render_project_nested_lists'
  app/views/projects/index.html.erb:12:in `_app_views_projects_index_html_erb___389564863150617922_55182460'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Regards,

**Comment by stgeneral** [comment]
@benoitlm please ensure that you use latest version of the plugin. To to Administration -> Plugins and ensure you have Progressive Projects List version **3.0.1**.

**Comment by benoitlm** [comment]
Effectively, I used 1.0.0 when I donwloaded the last package from : https://github.com/stgeneral/redmine-progressive-projects-list/archive/latest.zip

Now, I use last source from git and it's work fine.

Thanks.
