### ISSUE TITLE
Problem with project progress

### ISSUE THREAD

**Issue by mothsun** [stgeneral/redmine-progressive-projects-list#67]
I use redmine3.2 , no more other plugins . All of my projects display 100% progress , and the color is full of green in the progress bar , no matter the issues' status .

I modify   the file  `project_decorator.rb`:

``` ruby
  # Cloned from Version#completed_percent
  def issues_completed_percent
    if issues.count == 0
      0
    elsif issues.open.count == 0
      100 [ here I change it to 50 value , just a radom number ]
    else
      issues_progress(false) + issues_progress(true)
    end
  end
```

After that , the problem is solved . 
I do not understand .  
plz take a look ,  thx !

**Comment by stgeneral** [comment]
@mothsun do you use the latest version of the plugin? Version 3.0.1?

Version 3.0.1 is used on the several Redmine 3.2 installation without such issue.
Probably you have some custom settings/configuration?

**Comment by stgeneral** [comment]
Closing due to feedback absence.
