### ISSUE TITLE
Project 100%

### ISSUE THREAD

**Issue by mausampaio** [stgeneral/redmine-progressive-projects-list#68]
If a project has closed all issues the progress bar is no longer shown, it should not be at 100%?

I'm using Redmine 3.3

**Comment by stgeneral** [comment]
@mausampaio It would be great if you could provide a screenshot of the issue. 

Thank you.

**Comment by mausampaio** [comment]
No problem, here prints:

If i have 2 issues, 1 closed and 1 open:

![image](https://cloud.githubusercontent.com/assets/18605492/19435578/d05a0e36-9441-11e6-8435-9f3d24dc7943.png)

If I close the 2 issues, 
the progress bar disappears instead of being 100%.

![image](https://cloud.githubusercontent.com/assets/18605492/19435694/6a94e4f8-9442-11e6-968a-187e33e66382.png)

Thank you for the help.

**Comment by mausampaio** [comment]
https://github.com/stgeneral/redmine-progressive-projects-list/pull/69
