### ISSUE TITLE
Error message shown on Project Overview page

### ISSUE THREAD

**Issue by nadirlc** [stgeneral/redmine-progressive-projects-list#71]
![screenshot from 2017-01-09 14 40 36](https://cloud.githubusercontent.com/assets/20923812/21762351/0a37faee-d67a-11e6-83d8-852129ffba6a.png)
Hello,

The project overview page started showing an error after I activated the plugin. Please see attached screenshot.

Thanks,
Nadir Latif

**Comment by stgeneral** [comment]
@nadirlc seems you use inappropriate version of plugin or Redmine. Please check the compatibly https://github.com/stgeneral/redmine-progressive-projects-list#compatibility
