### ISSUE TITLE
Compatibility with Redmine 3.4.2.stable

### ISSUE THREAD

**Issue by keithkuk** [stgeneral/redmine-progressive-projects-list#74]
rake aborted!
Progressive Project List plugin directory should be 'progressive_projects_list' instead of 'redmine-progressive-projects-list'
/var/www/html/redmine/plugins/redmine-progressive-projects-list/init.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/www/html/redmine/lib/redmine/plugin.rb:146:in `each'
/var/www/html/redmine/lib/redmine/plugin.rb:146:in `load'
/var/www/html/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/www/html/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

Are there any plans to update the themes to Redmine 3.4.2.stable ?

Thanks a lot for your work.

**Comment by stgeneral** [comment]
Try to rename directory like it says in the error message:
> Progressive Project List plugin directory should be 'progressive_projects_list' instead of 'redmine-progressive-projects-list'

Thank you.
