### ISSUE TITLE
Cannot install on redmine 3.4.6, errors on bundle

### ISSUE THREAD

**Issue by rayures** [stgeneral/redmine-progressive-projects-list#79]
tried to install this plugin om my redmine instance. Unfortunately it did not work. 

getting errors on bundle.

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.7-p456 (2018-03-28) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                 production
  Database adapter               PostgreSQL

please ask if more info is needed.

**Comment by rayures** [comment]
Hmm, when collecting logs for you it suddenly works.

Made a copy of production, cleaned all and did a git clone. Renamed the plugin folder and bundle and a restart. plugin works :-) 
Earlier i did the same and it did not work, all kinds of gem errors. 

Now only a solution for the 2 column layout in the project overview. But i think that is a Redmine thing.

Tnx for your work on the plugin! much appreciated.

**Comment by stgeneral** [comment]
Thanks! Happy using plugin 👍
