### ISSUE TITLE
Internal error on Overiew page

### ISSUE THREAD

**Issue by sepahram** [stgeneral/redmine-progressive-projects-list#85]
I'm getting this "internal error (500) on Overview page of projects. Although, it's OK on Roadmap.

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  progressive_projects_list      3.0.1

BTW, it doesn't matter which combination of checkboxes I set. Even if all checks are off.

![progressive projects list plugin](https://user-images.githubusercontent.com/41936290/46060084-a397d480-c16e-11e8-8310-69a2bcb1bbab.jpg)

**Comment by stgeneral** [comment]
Can you please try to install the plugin from the PR #84 and let me know if it works correctly?

**Comment by sepahram** [comment]
I got and apply the new code. It solved part of the problem, which is before adding Target version.
As soon as I add a new version (with or without assigning an issue to it), I'm getting the same error. 

By the way, It' OK on Roadmap. 
![redmine-progressing-roadmap](https://user-images.githubusercontent.com/41936290/46241430-b4428780-c3c6-11e8-9067-5ed696089662.jpg)

**Comment by Ataeifard** [comment]
Escape the percent in '%0.0f%%',
Tested on redmine 3.4.6, ruby 2.5.1

**Comment by alexckua** [comment]
Hi. I fixed it. Can you please try again to install the plugin from the PR #84?

**Comment by sepahram** [comment]
Worked all right.
Thanks.

**Comment by stgeneral** [comment]
Fixed by #84.
