### ISSUE TITLE
Is it possible to add export all projects list into excel(VCL) file?

### ISSUE THREAD

**Issue by uart-aplex** [stgeneral/redmine-progressive-projects-list#93]
Is it possible to add export all projects list into excel(VCL) file by some filter option(like issues filter and field option)?

**Comment by stgeneral** [comment]
Well, this plugin is focused on providing the UI adjustments and I don't think this plugin will ever be extended with such a huge feature. It probably could be a separate plugin e.g. "projects_export" or something like that and we can consider developing it for you on a commercial basis if needed.
